### PR TITLE
Feature - Table with pagination component

### PR DESCRIPTION
**Pull request by mdjamilkashemporosh**
Light:
image

Dark:
image

RTL:
image

### CODE REVIEW

**Review by markmead — CHANGES_REQUESTED** [review]
I asked you to use existing table and pagination components for this.

**Comment by mdjamilkashemporosh** [comment]
image


image

**Review by markmead — CHANGES_REQUESTED** [review]
Thank you for updating the component to use an existing table component. However, it doesn't look like you've used an existing pagination component.

I wonder if the table and pagination should be enclosed in the same border (separate element) to make them appear more connected.

**Comment by markmead** [comment]
It doesn't have to be this exactly but here's what I mean - https://play.tailwindcss.com/GTetEV2Rqb?layout=preview

I took an existing table component and pagination component and adjusted them to make something new.

**Comment by mdjamilkashemporosh** [comment]
Thank you for your feedback! I appreciate your observation regarding the pagination component. If you have any further suggestions or concerns, please feel free to share them. I value your input and look forward to improving the component based on your feedback.

**Comment by markmead** [comment]
Pushed a few tweaks based on your work, looks good! Will merge, thanks for your work on this! 🎉

**Pull request merged**
