### PR TITLE
Update - Add more error page components

### PR DESCRIPTION
**Pull request by felixmacaspac**
added a new 404 page.

Hacktoberfest PR.

### CODE REVIEW

**Comment by markmead** [comment]
Hey @felixmacaspac this doesn't appear to take in the error page components that I added, might need to rebase.

**Comment by felixmacaspac** [comment]
Sure thing! hang on.

**Comment by markmead** [comment]
It looks great @felixmacaspac! 

Here are a few tweaks that I was thinking of, let me know what you think.

```html
<div class="grid h-screen place-content-center bg-white dark:bg-gray-900">
  <div class="text-center">
    <strong class="text-9xl font-black text-gray-700">404</strong>

    <h1 class="text-2xl font-bold tracking-tight text-white sm:text-4xl">Uh-oh!</h1>

    <p class="mt-4 text-gray-300">We can't find that page.</p>

    <a href="#" class="mt-6 inline-block rounded border border-indigo-600 bg-indigo-600 px-5 py-3 text-sm font-medium text-white hover:bg-transparent hover:text-indigo-600 focus:outline-none focus:ring active:text-indigo-500"> Go Back Home </a>
  </div>
</div>
```

Need to check how that `404` scales with `text-9xl` 😅

**Comment by felixmacaspac** [comment]
Hi, @markmead I followed some of your recommendations, Thanks for that! Let me know if I still need to revise something, thank you!

**Comment by markmead** [comment]
Looks good to me @felixmacaspac! Do you have any more you want to add?

**Comment by felixmacaspac** [comment]
That is all for me. Thank you!

**Pull request merged**
