### PR TITLE
Hotfix - Side menu hover issue

### PR DESCRIPTION
**Pull request by Xing97**
Make the hover only work on the icon and not outside the icon.

### CODE REVIEW

**Comment by markmead** [comment]
No idea what you're solving with this, the preview looks the same as the live site.

**Comment by Xing97** [comment]
Fixes this weird interaction
image

**Comment by markmead** [comment]
Huh, I don't have that experience with Chrome on Mac. Looks like you're using Windows, is it Chrome as well?

**Comment by Xing97** [comment]
I'm using Brave on Windows

**Comment by markmead** [comment]
Ah OK! Yeah looks broke on that, thanks for fixing!

**Pull request merged**
