### PR TITLE
Feature - Rate limit requests

### PR DESCRIPTION
**Pull request by markmead**
Setting up a rate limit to help prevent bandwidth usage attacks! 🤞

### CODE REVIEW

**Comment by markmead** [comment]
Hey @leerob, I'm not sure if you'll see this but you mentioned setting up rate limiting on this issue on Hypercolor - https://github.com/jordihales/hypercolor/issues/69 and I was wondering if I could pick your brain.

- How do I create a `/blocked` page? 
I've tried adding it in `/app` and the `/public` folder but it just hits the `not-found.jsx` page.
- How does this effect local development? I have it disabled for the `development` environment, am I safe in assuming it would have no impact?

Also, in the guide it mentions `@upstash/rate-limit` when it should be `@upstash/ratelimit`.

**Comment by leerob** [comment]
You can make a new file at `app/blocked/page.js` for the `/blocked` route to rewrite to. Is that not working for you?

**Comment by markmead** [comment]
> You can make a new file at `app/blocked/page.js` for the `/blocked` route to rewrite to. Is that not working for you?

I tried that but it was still hitting the 404. I'll take another look. Thank you.

**Comment by markmead** [comment]
OK that seems to be working now @leerob, I think I had the page export as `Custom404`! 🤦‍♀️ 

Sorry, I called you over for something so trivial! Thanks for the help.

**Pull request merged**
